module.exports = {
  root: true,
  env: {
    es2021: true,
    node: true,
  },
  extends: ["airbnb-base", "airbnb-typescript/base", "prettier"],
  parser: "@typescript-eslint/parser",
  parserOptions: {
    project: "./tsconfig.json",
    ecmaVersion: 2021,
    sourceType: "module",
  },
  plugins: ["@typescript-eslint", "unused-imports", "prettier"],
  rules: {
  	"arrow-body-style": "off",
    "no-constant-condition": "off",
    "vars-on-top": "off",
    "no-plusplus": "off",
    "no-continue": "off",
    "no-alert": "off",
    "no-await-in-loop": "off",
    radix: "off",
    "consistent-return": "off",
    "no-underscore-dangle": "off",
    "max-classes-per-file": "off",
    camelcase: "off",
    "no-console": "off",
    "class-methods-use-this": "off",
    "@typescript-eslint/default-param-last": "off",
    "@typescript-eslint/no-unused-vars": "warn",
    "@typescript-eslint/naming-convention": "off",
    "prettier/prettier": [
      "error",
      {
        tabWidth: 2,
        printWidth: 120,
        singleQuote: false,
        useTabs: true,
        quoteProps: "consistent",
        bracketSameLine: true,
        trailingComma: "es5",
        arrowParens: "always",
        semi: true,
      },
    ],
    "import/first": "error",
    "import/exports-last": "off",
    "import/extensions": "off",
    "import/order": [
      "error",
      {
        groups: [
          "builtin",
          "external",
          "internal",
          "index",
          "sibling",
          "parent",
          "object",
          "type",
        ],
        "newlines-between": "always",
        alphabetize: {
          order: "asc",
          caseInsensitive: true,
        },
      },
    ],
    "import/newline-after-import": "error",
    "import/no-named-as-default": "off",
    "import/prefer-default-export": "off",
    "unused-imports/no-unused-imports": "error",
  },
};
